# Generated by Django 2.1 on 2019-07-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Адрес электронной почты')),
                ('name', models.CharField(blank=True, default='', max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Администратор', 'Администратор'), ('Менеджер', 'Менеджер')], db_index=True, default='Менеджер', max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Месторождение',
                'verbose_name_plural': 'Месторождения',
            },
        ),
        migrations.CreateModel(
            name='FieldBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_balance', models.FloatField(db_index=True, default=0, verbose_name='Автомобильные весы (жидкость)')),
                ('ansagan_balance', models.FloatField(db_index=True, default=0, verbose_name='Весы по Ансаган (жидкость)')),
                ('transport_brutto', models.FloatField(db_index=True, default=0, verbose_name='Автомобильные весы (брутто)')),
                ('ansagan_brutto', models.FloatField(db_index=True, default=0, verbose_name='Весы по Ансаган (брутто)')),
                ('transport_netto', models.FloatField(db_index=True, default=0, verbose_name='Автомобильные весы (нетто)')),
                ('ansagan_netto', models.FloatField(db_index=True, default=0, verbose_name='Весы по Ансаган (нетто)')),
                ('transport_density', models.FloatField(db_index=True, default=0, verbose_name='Автомобильные весы (плотность)')),
                ('ansagan_density', models.FloatField(db_index=True, default=0, verbose_name='Весы по Ансаган (плотность)')),
                ('agzu_fluid', models.FloatField(db_index=True, default=0, verbose_name='Замер жидкости по скважинам')),
                ('agzu_oil', models.FloatField(db_index=True, default=0, verbose_name='Замер нефти по скважинам')),
                ('teh_rej_fluid', models.FloatField(db_index=True, default=0, verbose_name='Замер по Тех. жидкости')),
                ('teh_rej_oil', models.FloatField(db_index=True, default=0, verbose_name='Замер по Тех. нефти')),
                ('timestamp', models.DateField(verbose_name='Дата замера')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bal_fields', to='main.Field')),
            ],
            options={
                'verbose_name': 'Баланс по месторождению',
                'verbose_name_plural': 'Баланс по месторождениям',
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название')),
                ('teh_rej_fluid', models.FloatField(default=0, verbose_name='Техрежим жидкости')),
                ('teh_rej_oil', models.FloatField(default=0, verbose_name='Техрежим нефти')),
                ('teh_rej_water', models.FloatField(default=0, verbose_name='Обводненность')),
                ('production_type', models.CharField(choices=[('ШГН', 'ШГН'), ('ЭВН', 'ЭВН')], default='ШГН', max_length=100, verbose_name='Технология добычи')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='main.Field')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
            },
        ),
        migrations.CreateModel(
            name='WellMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluid_agzu', models.FloatField(db_index=True, default=0, verbose_name='Жидкость (АГЗУ)')),
                ('fluid_isu', models.FloatField(db_index=True, default=0, verbose_name='Жидкость (ИСУ)')),
                ('shortage_isu', models.FloatField(db_index=True, default=0, verbose_name='Недобор (ИСУ)')),
                ('shortage_prs', models.FloatField(db_index=True, default=0, verbose_name='Недобор (ПРС)')),
                ('shortage_wait', models.FloatField(db_index=True, default=0, verbose_name='Недобор (Ожид.тех)')),
                ('well_stop', models.FloatField(db_index=True, default=0, verbose_name='Остановы')),
                ('oil_loss', models.FloatField(db_index=True, default=0, verbose_name='Потери')),
                ('active', models.BooleanField(default=False, verbose_name='Активный')),
                ('performance', models.FloatField(default=100, verbose_name='Производительность')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Матрица ИСУ',
                'verbose_name_plural': 'Матрица ИСУ',
            },
        ),
    ]
