# Generated by Django 2.1 on 2019-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellmatrix',
            name='filling',
            field=models.FloatField(default=0, verbose_name='Заполнение насоса'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='fluid_agzu',
            field=models.FloatField(default=0, verbose_name='Жидкость (АГЗУ)'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='fluid_isu',
            field=models.FloatField(default=0, verbose_name='Жидкость (ИСУ)'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='oil_loss',
            field=models.FloatField(default=0, verbose_name='Потери'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='shortage_isu',
            field=models.FloatField(default=0, verbose_name='Недобор (ИСУ)'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='shortage_prs',
            field=models.FloatField(default=0, verbose_name='Недобор (ПРС)'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='shortage_wait',
            field=models.FloatField(default=0, verbose_name='Недобор (Ожид.тех)'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='well_stop',
            field=models.FloatField(default=0, verbose_name='Остановы'),
        ),
    ]
