# Generated by Django 2.1 on 2019-08-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190808_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('densityPL', models.FloatField(default=0, verbose_name='Давление (Пласт)')),
                ('densityZB', models.FloatField(default=0, verbose_name='Давление (Забой)')),
                ('densityDiff', models.FloatField(default=0, verbose_name='Разница')),
                ('fluid_av', models.FloatField(default=0, verbose_name='Жидкость (ср.)')),
                ('timestamp', models.DateField(verbose_name='Дата')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depression_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Подбор депрессии',
                'verbose_name_plural': 'Подбор депрессий',
            },
        ),
    ]
