# Generated by Django 2.1 on 2019-08-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_depression'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellmatrix',
            options={'verbose_name': 'Матрица', 'verbose_name_plural': 'Матрица'},
        ),
        migrations.AddField(
            model_name='wellmatrix',
            name='brigade_num',
            field=models.IntegerField(default=0, verbose_name='Номер бригады'),
        ),
        migrations.AddField(
            model_name='wellmatrix',
            name='ts_num',
            field=models.FloatField(default=0, verbose_name='Номер ТС'),
        ),
    ]
