# Generated by Django 2.1 on 2019-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190814_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellmatrix',
            name='ts_num',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер ТС'),
        ),
    ]
