# Generated by Django 2.1 on 2019-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190814_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellmatrix',
            name='has_isu',
            field=models.BooleanField(default=False, verbose_name='Оснащен ИСУ'),
        ),
    ]
