# Generated by Django 2.1 on 2019-08-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ts',
            name='gos_num',
            field=models.CharField(max_length=20, verbose_name='Гос номер'),
        ),
    ]
