# Generated by Django 2.1 on 2019-08-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190816_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_pair', models.IntegerField(default=-1, verbose_name='Пара')),
                ('pre_fluid', models.FloatField(default=0, verbose_name='Жидкость (До)')),
                ('post_fluid', models.FloatField(default=0, verbose_name='Жидкость (После)')),
                ('pre_oil', models.FloatField(default=0, verbose_name='Нефть (До)')),
                ('post_oil', models.FloatField(default=0, verbose_name='Нефть (После)')),
                ('pre_obv', models.FloatField(default=0, verbose_name='Нефть (До)')),
                ('post_obv', models.FloatField(default=0, verbose_name='Нефть (После)')),
                ('effect', models.FloatField(default=0, verbose_name='Эффект (нефть)')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Профиль добычи',
                'verbose_name_plural': 'Профиль добычи',
            },
        ),
    ]
