# Generated by Django 2.1 on 2019-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_prodprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodprofile',
            name='post_obv',
            field=models.FloatField(default=0, verbose_name='Обводненность (После)'),
        ),
        migrations.AlterField(
            model_name='prodprofile',
            name='pre_obv',
            field=models.FloatField(default=0, verbose_name='Обводненность (До)'),
        ),
    ]
