# Generated by Django 2.1 on 2019-08-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190817_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gos_num', models.CharField(max_length=20, verbose_name='Гос номер')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('year', models.IntegerField(default=2019, verbose_name='Год')),
                ('field', models.CharField(max_length=50, verbose_name='ПСП')),
                ('gsm_type', models.CharField(max_length=30, verbose_name='Тип ГСМ')),
                ('sum', models.FloatField(default=0, verbose_name='Сумма во ВВ')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'ГСМ',
                'verbose_name_plural': 'ГСМ',
            },
        ),
        migrations.AlterField(
            model_name='ts',
            name='year',
            field=models.IntegerField(default=2019, verbose_name='Год'),
        ),
    ]
