# Generated by Django 2.1 on 2019-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_gsm_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsm',
            name='month',
            field=models.IntegerField(default=-1, verbose_name='Месяц'),
        ),
    ]
