# Generated by Django 2.1 on 2019-08-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190827_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsm',
            name='field',
            field=models.CharField(max_length=30, verbose_name='ПСП'),
        ),
        migrations.AlterField(
            model_name='gsm',
            name='gos_num',
            field=models.CharField(max_length=50, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='gsm',
            name='gsm_type',
            field=models.CharField(max_length=50, verbose_name='Тип ГСМ'),
        ),
        migrations.AlterField(
            model_name='gsm',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
    ]
