# Generated by Django 2.1 on 2019-10-14 10:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190827_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('y', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('timestamp', models.DateTimeField(verbose_name='Время замера')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dyn_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Динамограмма скважины',
                'verbose_name_plural': 'Динамограммы скважин',
            },
        ),
    ]
