# Generated by Django 2.1 on 2019-11-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_dynamogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imbalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imbalance', models.FloatField(default=0, verbose_name='Неуравновешенность')),
                ('avg_1997', models.FloatField(default=0, verbose_name='Заполнения насоса')),
                ('timestamp', models.DateTimeField(verbose_name='Дата опроса')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imb_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Неуравновешенность',
                'verbose_name_plural': 'Неуравновешенность',
            },
        ),
    ]
