# Generated by Django 2.1 on 2020-01-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20191120_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImbalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imbalance', models.FloatField(default=0, verbose_name='Неуравновешенность')),
                ('avg_1997', models.FloatField(default=0, verbose_name='Заполнения насоса')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Дата опроса')),
                ('imb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imb', to='main.Imbalance')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imb_wells_history', to='main.Well')),
            ],
            options={
                'verbose_name': 'Неуравновешенность история',
                'verbose_name_plural': 'Неуравновешенность история',
            },
        ),
    ]
