# Generated by Django 2.1 on 2020-02-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200201_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumwellinfield',
            name='active',
        ),
        migrations.RemoveField(
            model_name='sumwellinfield',
            name='brigade_num',
        ),
        migrations.RemoveField(
            model_name='sumwellinfield',
            name='has_isu',
        ),
        migrations.RemoveField(
            model_name='sumwellinfield',
            name='oil_loss',
        ),
        migrations.RemoveField(
            model_name='sumwellinfield',
            name='ts_num',
        ),
        migrations.RemoveField(
            model_name='wellmatrix',
            name='oil_loss',
        ),
    ]
