# Generated by Django 2.1 on 2020-02-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200201_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='server',
            field=models.CharField(choices=[('192.168.241.2', '192.168.241.2'), ('192.168.243.2', '192.168.243.2'), ('192.168.236.2', '192.168.236.2'), ('192.168.128.2', '192.168.128.2')], default='192.168.241.2', max_length=15, verbose_name='Сервер'),
        ),
        migrations.AddField(
            model_name='well',
            name='well_id',
            field=models.IntegerField(default=0, verbose_name='id well'),
        ),
    ]
