# Generated by Django 2.1 on 2020-02-27 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200203_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ПРС', 'ПРС'), ('КРС', 'КРС'), ('ТРС', 'ТРС'), ('Прочее', 'Прочее')], default='Прочее', max_length=20, verbose_name='Тип события')),
                ('event', models.CharField(max_length=200, verbose_name='Событие')),
                ('beg', models.DateTimeField(verbose_name='Начало события')),
                ('end', models.DateTimeField(verbose_name='Конец события')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Журнал события',
                'verbose_name_plural': 'Журнал событий',
            },
        ),
    ]
