# Generated by Django 2.1 on 2020-03-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200227_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='has_isu',
            field=models.BooleanField(default=False, verbose_name='Оснащен ИСУ'),
        ),
    ]
