# Generated by Django 2.1 on 2020-03-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_well_has_isu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filling', models.FloatField(default=0, verbose_name='Заполнение насоса')),
                ('fluid_agzu', models.FloatField(default=0, verbose_name='Жидкость (АГЗУ)')),
                ('fluid_isu', models.FloatField(default=0, verbose_name='Жидкость (ИСУ)')),
                ('shortage_isu', models.FloatField(default=0, verbose_name='Недобор (ИСУ)')),
                ('shortage_prs', models.FloatField(default=0, verbose_name='Недобор (ПРС)')),
                ('shortage_wait', models.FloatField(default=0, verbose_name='Недобор (Ожид.тех)')),
                ('teh_rej_fluid', models.FloatField(default=0, verbose_name='Техрежим жидкости')),
                ('teh_rej_oil', models.FloatField(default=0, verbose_name='Техрежим нефти')),
                ('teh_rej_water', models.FloatField(default=0, verbose_name='Обводненность')),
                ('well_stop', models.FloatField(default=0, verbose_name='Остановы')),
                ('performance', models.FloatField(default=100, verbose_name='Производительность')),
                ('timestamp', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_fields', to='main.Field')),
            ],
        ),
    ]
