# Generated by Django 2.1 on 2020-03-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_fieldmatrix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldmatrix',
            options={'verbose_name': 'Матрица месторождении', 'verbose_name_plural': 'Матрица месторождений'},
        ),
        migrations.AlterModelOptions(
            name='sumwellinfield',
            options={'verbose_name': 'Матрица месторождении (ИСУ)', 'verbose_name_plural': 'Матрица месторождений (ИСУ)'},
        ),
    ]
