# Generated by Django 2.1 on 2020-04-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200304_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellevents',
            name='event_type',
            field=models.CharField(choices=[('ПРС', 'ПРС'), ('КРС', 'КРС'), ('ТРС', 'ТРС'), ('Прочие простои', 'Прочие простои')], default='Прочие простои', max_length=20, verbose_name='Тип события'),
        ),
    ]
