# Generated by Django 2.1 on 2020-04-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200407_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldmatrix',
            name='shortage_isu',
        ),
        migrations.RemoveField(
            model_name='fieldmatrix',
            name='shortage_prs',
        ),
        migrations.RemoveField(
            model_name='fieldmatrix',
            name='shortage_wait',
        ),
        migrations.RemoveField(
            model_name='fieldmatrix',
            name='well_stop',
        ),
        migrations.RemoveField(
            model_name='sumwellinfield',
            name='shortage_isu',
        ),
        migrations.RemoveField(
            model_name='sumwellinfield',
            name='shortage_prs',
        ),
        migrations.RemoveField(
            model_name='sumwellinfield',
            name='shortage_wait',
        ),
        migrations.RemoveField(
            model_name='sumwellinfield',
            name='well_stop',
        ),
        migrations.RemoveField(
            model_name='wellmatrix',
            name='brigade_num',
        ),
        migrations.RemoveField(
            model_name='wellmatrix',
            name='shortage_isu',
        ),
        migrations.RemoveField(
            model_name='wellmatrix',
            name='shortage_prs',
        ),
        migrations.RemoveField(
            model_name='wellmatrix',
            name='shortage_wait',
        ),
        migrations.RemoveField(
            model_name='wellmatrix',
            name='ts_num',
        ),
        migrations.RemoveField(
            model_name='wellmatrix',
            name='well_stop',
        ),
        migrations.AddField(
            model_name='well',
            name='brigade_num',
            field=models.IntegerField(default=0, verbose_name='Номер бригады'),
        ),
        migrations.AddField(
            model_name='well',
            name='shortage_isu',
            field=models.FloatField(default=0, verbose_name='Недобор (ИСУ)'),
        ),
        migrations.AddField(
            model_name='well',
            name='shortage_prs',
            field=models.FloatField(default=0, verbose_name='Недобор (ПРС)'),
        ),
        migrations.AddField(
            model_name='well',
            name='shortage_wait',
            field=models.FloatField(default=0, verbose_name='Недобор (Ожид.тех)'),
        ),
        migrations.AddField(
            model_name='well',
            name='ts_num',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер ТС'),
        ),
        migrations.AddField(
            model_name='well',
            name='well_stop',
            field=models.FloatField(default=0, verbose_name='Остановы'),
        ),
    ]
