# Generated by Django 2.1 on 2020-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_well_well_stop_prs'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='rem_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во ремонтов'),
        ),
    ]
