# Generated by Django 2.1 on 2020-04-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200415_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellevents',
            name='event_type',
            field=models.CharField(choices=[('ПРС', 'ПРС'), ('КРС', 'КРС'), ('ТРС', 'ТРС'), ('ГТМ', 'ГТМ'), ('Прочие простои', 'Прочие простои')], default='Прочие простои', max_length=20, verbose_name='Тип события'),
        ),
    ]
