# Generated by Django 2.1 on 2020-09-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_prsdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Значение')),
                ('min', models.FloatField(default=0, verbose_name='Минимум')),
                ('max', models.FloatField(default=0, verbose_name='Максимум')),
            ],
            options={
                'verbose_name': 'Уставка',
                'verbose_name_plural': 'Уставки',
            },
        ),
        migrations.AddField(
            model_name='wellmatrix',
            name='kpn',
            field=models.FloatField(default=1, verbose_name='Коэф. подачи насоса'),
        ),
    ]
