# Generated by Django 2.1 on 2020-09-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200923_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200, verbose_name='Рекомендация')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Дата рекомендации')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Журнал рекомендации',
                'verbose_name_plural': 'Журнал рекомендаций',
            },
        ),
    ]
