# Generated by Django 2.1 on 2020-10-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_recommendation_kpn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200, verbose_name='Событие')),
                ('event_type', models.CharField(choices=[('ПРС', 'ПРС'), ('КРС', 'КРС'), ('ТРС', 'ТРС'), ('ГТМ', 'ГТМ'), ('Прочие простои', 'Прочие простои')], default='Прочие простои', max_length=20, verbose_name='Тип события')),
                ('fact', models.FloatField(default=0, verbose_name='Факт кол-во')),
                ('plan', models.FloatField(default=0, verbose_name='План кол-во')),
                ('coef', models.FloatField(default=0, verbose_name='Доля от общего кол-во')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('effect', models.FloatField(default=0, verbose_name='Доп. добыча')),
            ],
            options={
                'verbose_name': 'Статистика события',
                'verbose_name_plural': 'Статистика событий',
            },
        ),
        migrations.AddField(
            model_name='wellmatrix',
            name='park_fluid',
            field=models.FloatField(default=-1, verbose_name='Парковая жидкость'),
        ),
        migrations.AddField(
            model_name='wellmatrix',
            name='park_oil',
            field=models.FloatField(default=-1, verbose_name='Парковая нефть'),
        ),
    ]
