# Generated by Django 2.1 on 2020-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20201008_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='fact',
            field=models.IntegerField(default=0, verbose_name='Факт кол-во'),
        ),
        migrations.AlterField(
            model_name='events',
            name='plan',
            field=models.IntegerField(default=0, verbose_name='План кол-во'),
        ),
    ]
