# Generated by Django 2.1 on 2020-12-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20201208_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailuser',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='mailuser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ф.И.О.'),
        ),
    ]
