# Generated by Django 2.1 on 2020-12-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20201208_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsettings',
            name='body',
            field=models.CharField(max_length=60, verbose_name='Тема письма'),
        ),
    ]
