# Generated by Django 2.1 on 2020-12-25 19:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20201209_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wattmetrogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('y', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('timestamp', models.DateTimeField(verbose_name='Время замера')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watt_wells', to='main.Well')),
            ],
            options={
                'verbose_name': 'Ваттметрограмма скважины',
                'verbose_name_plural': 'Ваттметрограммы скважин',
            },
        ),
    ]
