# Generated by Django 2.1 on 2020-12-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_wattmetrogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_fields', to='main.Field'),
        ),
    ]
