# Generated by Django 2.1 on 2020-12-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_events_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='gzu',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ГЗУ'),
        ),
        migrations.AddField(
            model_name='well',
            name='horizon',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Горизонт'),
        ),
    ]
