# Generated by Django 2.1 on 2020-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20201226_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellmatrix',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='wellmatrix',
            name='tbd_fluid',
            field=models.FloatField(default=-1, verbose_name='ТБД жидкость'),
        ),
    ]
