# Generated by Django 2.1 on 2021-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20201226_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmatrix',
            name='filling',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Заполнение насоса'),
        ),
        migrations.AlterField(
            model_name='fieldmatrix',
            name='fluid_agzu',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Жидкость (АГЗУ)'),
        ),
        migrations.AlterField(
            model_name='fieldmatrix',
            name='fluid_isu',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Жидкость (ИСУ)'),
        ),
        migrations.AlterField(
            model_name='fieldmatrix',
            name='teh_rej_fluid',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Техрежим жидкости'),
        ),
        migrations.AlterField(
            model_name='fieldmatrix',
            name='teh_rej_oil',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Техрежим нефти'),
        ),
        migrations.AlterField(
            model_name='fieldmatrix',
            name='teh_rej_water',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Обводненность'),
        ),
        migrations.AlterField(
            model_name='sumwellinfield',
            name='filling',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Заполнение насоса'),
        ),
        migrations.AlterField(
            model_name='sumwellinfield',
            name='fluid_agzu',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Жидкость (АГЗУ)'),
        ),
        migrations.AlterField(
            model_name='sumwellinfield',
            name='fluid_isu',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Жидкость (ИСУ)'),
        ),
        migrations.AlterField(
            model_name='sumwellinfield',
            name='teh_rej_fluid',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Техрежим жидкости'),
        ),
        migrations.AlterField(
            model_name='sumwellinfield',
            name='teh_rej_oil',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Техрежим нефти'),
        ),
        migrations.AlterField(
            model_name='sumwellinfield',
            name='teh_rej_water',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Обводненность'),
        ),
    ]
