# Generated by Django 2.1 on 2021-01-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20210106_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellmatrix',
            name='p_plast',
            field=models.FloatField(default=0, verbose_name='Давление (пл)'),
        ),
        migrations.AddField(
            model_name='wellmatrix',
            name='p_zab',
            field=models.FloatField(default=0, verbose_name='Давление (заб)'),
        ),
    ]
