# Generated by Django 2.1 on 2021-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20210107_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellmatrix',
            name='sdmo_status',
            field=models.FloatField(default=1, verbose_name='Статус (сдмо)'),
        ),
        migrations.AddField(
            model_name='wellmatrix',
            name='tpn',
            field=models.FloatField(default=1, verbose_name='ТПН'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='kpn',
            field=models.FloatField(default=1, verbose_name='КПН'),
        ),
        migrations.AlterField(
            model_name='wellmatrix',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Статус (тбд)'),
        ),
    ]
